### ISSUE TITLE
`reset-application-fixture` hardcodes bootstrap.servers value

### ISSUE THREAD

**Issue by timclemons** [FundingCircle/jackdaw#176]
Attempting to use `reset-application-fixture` or, by extension, `integration-fixture` with a Kafka bootstrap server other than localhost:9092 results in a connection timeout.  Examining the source, it looks like this value has been hardcoded as an argument to `StreamsResetter`.

**Comment by cddr** [comment]
Thanks for the bug report @timclemons. @7vs is taking a look at this

**Comment by cddr** [comment]
Closed by #177
