### ISSUE TITLE
Add jackdaw.streams/split?

### ISSUE THREAD

**Issue by AlexVPopov** [FundingCircle/jackdaw#232]
Would it make sense to add:

```clojure
(jackdaw.streams/split kstream pred-fn)
```

which is essentially:

```clojure
(jackdaw.streams/branch kstream [pred-fn (complement pred-fn)])
```

or is this case too trivial?

**Comment by minimal** [comment]
`branch` already splits the stream so it's also the equivalent of `(jackdaw.streams/branch kstream [pred-fn any?])`

**Comment by AlexVPopov** [comment]
O.K., I see. I find `js/splt` version a bit more expressive, but on the other hand `any?` is also pretty straightforward 👍
