### ISSUE TITLE
Is `aleph` really needed under the top-level dependencies?

### ISSUE THREAD

**Issue by jimpil** [FundingCircle/jackdaw#267]
Hi there,

Correct me if I'm wrong, but `aleph` is only needed in a couple of test namespaces. If that's correct, how come it's included as a top-level dependency? There is already a `dev` profile where it can go, right?

Thanks in advance...

**Comment by cddr** [comment]
The test machine is part of the public interface and provides support for testing kafka applications. See the docs [here](https://cljdoc.org/d/fundingcircle/jackdaw/0.7.6/doc/the-test-machine). This is what requires the dependency on aleph.

**Comment by jimpil** [comment]
Oh I see - thanks a lot for clarifying :+1:
