### ISSUE TITLE
Update Jackdaw to work with newer versions of kafka-streams / kafka-streams-test-utils

### ISSUE THREAD

**Issue by LouiseKlodt** [FundingCircle/jackdaw#290]
Currently, the `jackdaw.test` namespace requires you to import `TopologyTestDriver` for `test-machine` to work, which in turn requires you to bring in the `org.apache.kafka/kafka-streams-test-utils` library as a dependency. 

This currently only works using a `kafka-streams-test-utils` version within `2.0.0` - `2.3.0`. When adding versions higher than ` 2.3.0`, it throws errors. For example, for version `2.4.0`:

```
Syntax error (ClassNotFoundException) compiling new at (jackdaw/test.clj:250:5).
org.apache.kafka.streams.internals.QuietStreamsConfig
```

Errors are thrown for version numbers from `2.4.0, 2.5.0` ... up to the latest: `2.8.0` - they all occur in `jackdaw/test.clj`.

-> Jackdaw needs to be made compatible / brought up to date with the newest versions from Apache Kafka's libraries.

**Comment by cddr** [comment]
I think the only thing I needed to do to get it working on later versions of kafka (other than updating dependencies) was to ensure `new-topic` cast ints to shorts which is required by upstream API now.

https://github.com/cddr/test-machine/compare/cfab170..75bcf2e#diff-95c6c5e52b1f9ddf661e9b7feec305c82cf4881c99bbc782a8610ec108f0ee95R22

https://github.com/cddr/test-machine/compare/cfab170..75bcf2e

**Comment by gphilipp** [comment]
Thanks Andy, we're going to have a look next week.
