### ISSUE TITLE
0.9.0 release did not work 

### ISSUE THREAD

**Issue by kidpollo** [FundingCircle/jackdaw#306]
https://app.circleci.com/pipelines/github/FundingCircle/jackdaw/1126/workflows/ff906447-634e-45f0-8a16-ad24a5e15ad8/jobs/3865

**Comment by 99-not-out** [comment]
We're on it my friend - trying to sort it out. SSH key / GPG key issues ...

**Comment by 99-not-out** [comment]
@kidpollo  - 0.9.1 is released now
