### ISSUE TITLE
support foreign key joins

### ISSUE THREAD

**Issue by raymcdermott** [FundingCircle/jackdaw#364]
Add support for the `join` arity that accepts a `foreign-key-extractor` function

### Blog post that introduces the feature
https://www.confluent.io/blog/data-enrichment-with-kafka-streams-foreign-key-joins/

### Official API
https://kafka.apache.org/24/javadoc/org/apache/kafka/streams/kstream/KTable.html#join-org.apache.kafka.streams.kstream.KTable-java.util.function.Function-org.apache.kafka.streams.kstream.ValueJoiner-

**Comment by minimal** [comment]
closed by #365
