### ISSUE TITLE
Strange names

### ISSUE THREAD

**Issue by AndreaCrotti** [FundingCircle/jackdaw#43]
Given that the test machine is just called `test` we end up with some interesting file names, like

- src/jackdaw/test.clj
- test/jackdaw/test_test.clj

I'm not sure what could be a better name tbh, but I think that the whole machinery under `src/test` is not really just useful to write tests, it's something that can help just setting up kafka topics, so it might be worth to rename it something else.

**Comment by 99-not-out** [comment]
Yeah - its in between the tools and testing worlds, tooling for building tests on top of ... and other things (like setups, monitors, injectors, ...). We couldn't think of a better name tho!

**Comment by cddr** [comment]
I agree that some of the code under src/test might be useful in other contexts but I'd suggest just copying it to where you'd like it to be and then it can evolve from there to fully match that new use-case. If a shared abstraction emerges, we can refactor at that point.
