### ISSUE TITLE
describe-topics-configs throws ClassCastException

### ISSUE THREAD

**Issue by dfbernal** [FundingCircle/jackdaw#9]
`(ja/describe-topics-configs client [{:topic-name "connect-offsets"}])` throws a ClassCastException when invoked. I think the fix is relatively simple just have to add topics to ```(-> client
      (.describeConfigs (map #(-> % :topic-name jd/->topic-resource) topics))
      .all deref vals first jd/datafy)```

**Comment by arrdem** [comment]
Wow. Yeah that never worked. Wonder how I checked it in. Thanks for the catch!
